'use client';

import { useSearchParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Sparkles, User, FileText, ShieldCheck, Download } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export default function SharedChatViewer() {
  const searchParams = useSearchParams();
  const [data, setData] = useState<{ title: string, author: string, chat: any[] } | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    try {
      const payload = searchParams.get('data');
      if (payload) {
        // Decode the URL-safe Base64 string back into the chat object
        const decodedString = decodeURIComponent(atob(payload));
        setData(JSON.parse(decodedString));
      } else {
        setError(true);
      }
    } catch (e) {
      console.error(e);
      setError(true);
    }
  }, [searchParams]);

  if (error) {
    return (
      <div className="flex h-screen w-screen bg-[#050505] text-white items-center justify-center font-sans">
        <div className="text-center space-y-4">
           <ShieldCheck className="w-12 h-12 text-zinc-600 mx-auto" />
           <h1 className="text-2xl font-semibold">Link Corrupted or Expired</h1>
           <p className="text-zinc-500">This shared workspace could not be decrypted.</p>
        </div>
      </div>
    );
  }

  if (!data) return <div className="h-screen w-screen bg-[#050505]" />;

  return (
    <div className="flex flex-col h-screen w-screen bg-[#050505] text-zinc-200 font-sans overflow-hidden">
      
      {/* Premium Header */}
      <header className="h-16 border-b border-white/5 flex items-center justify-between px-8 bg-[#0a0a0a] shrink-0">
        <div className="flex items-center space-x-3">
           <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-blue-400" />
           </div>
           <span className="font-semibold text-lg tracking-tight">Axiom-Zero <span className="text-zinc-600 font-normal">| Shared Workspace</span></span>
        </div>
        <div className="flex items-center space-x-3 text-xs font-medium text-zinc-500">
           <span className="flex items-center"><FileText className="w-4 h-4 mr-2 text-zinc-600" /> {data.title}</span>
        </div>
      </header>

      {/* Read-Only Chat Canvas */}
      <main className="flex-1 overflow-y-auto p-6 lg:p-12">
         <div className="max-w-3xl mx-auto space-y-8 pb-20">
            <div className="text-center mb-12">
               <p className="text-sm text-zinc-500 uppercase tracking-widest font-bold mb-2">Read-Only Session</p>
               <h2 className="text-3xl font-semibold text-white tracking-tight">Generated by {data.author}</h2>
            </div>

            {data.chat.map((msg, idx) => (
               <div key={idx} className={`flex w-full ${msg.r === 'user' ? 'justify-end' : 'justify-start'}`}>
                  <div className={`flex gap-4 ${msg.r === 'user' ? 'flex-row-reverse max-w-[85%]' : 'w-full min-w-0'}`}>
                     
                     <div className={`w-8 h-8 rounded-full flex items-center justify-center mt-1 shrink-0 ${msg.r === 'user' ? 'bg-zinc-800' : 'bg-blue-500/10 border border-blue-500/20'}`}>
                        {msg.r === 'user' ? <User className="w-4 h-4 text-zinc-400" /> : <Sparkles className="w-4 h-4 text-blue-400" />}
                     </div>
                     
                     <div className="flex flex-col w-full min-w-0">
                        {msg.r === 'user' ? (
                          <div className="px-5 py-3.5 rounded-2xl bg-[#1e1e1e] border border-white/5 text-zinc-100 text-[15px] leading-relaxed">
                              {msg.c}
                          </div>
                        ) : (
                          <div className="text-[15px] leading-relaxed font-open-sans text-zinc-200 prose prose-invert max-w-none pt-1.5">
                              <ReactMarkdown>{msg.c}</ReactMarkdown>
                          </div>
                        )}
                     </div>

                  </div>
               </div>
            ))}
         </div>
      </main>

      {/* Footer Banner */}
      <div className="h-12 bg-blue-600 flex items-center justify-center text-white text-xs font-medium tracking-wide">
         You are viewing a shared snapshot of an Axiom-Zero local session.
      </div>
    </div>
  );
}